# Generated by Django 4.1.1 on 2022-09-28 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notic',
            name='top_fixed',
        ),
        migrations.CreateModel(
            name='NoticHits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notic_client_ip', models.GenericIPAddressField(null=True, verbose_name='사용자 IP주소')),
                ('data', models.DateField(auto_now_add=True, verbose_name='조회날짜')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.notic', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '조회수 모델',
                'verbose_name_plural': '조회수 모델',
                'db_table': '공지사항 조회수',
            },
        ),
    ]
