# Generated by Django 4.1.1 on 2022-09-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='producet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('about', models.TextField()),
                ('price', models.TextField()),
                ('image', models.ImageField(upload_to='static/shop_img/img/')),
            ],
        ),
        migrations.DeleteModel(
            name='proucet',
        ),
    ]
