# Generated by Django 4.1.1 on 2022-09-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_producet_delete_proucet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producet',
            name='price',
        ),
    ]
