# Generated by Django 4.1.1 on 2022-09-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_producet_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='au',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='upload_file/shop_img/au_img/')),
            ],
        ),
        migrations.CreateModel(
            name='emc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='upload_file/shop_img/emc_img/')),
            ],
        ),
        migrations.CreateModel(
            name='mnc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='upload_file/shop_img/mnc_img/')),
            ],
        ),
        migrations.CreateModel(
            name='na',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='upload_file/shop_img/na_img/')),
            ],
        ),
        migrations.CreateModel(
            name='oscillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='upload_file/shop_img/osi_img/')),
            ],
        ),
        migrations.CreateModel(
            name='pm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='upload_file/shop_img/pm_img/')),
            ],
        ),
        migrations.CreateModel(
            name='ps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='upload_file/shop_img/ps_img/')),
            ],
        ),
        migrations.CreateModel(
            name='sa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='upload_file/shop_img/sa_img/')),
            ],
        ),
        migrations.CreateModel(
            name='sg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='upload_file/shop_img/sg_img/')),
            ],
        ),
        migrations.DeleteModel(
            name='producet',
        ),
    ]
